data:
  download:
    name: 'ares_tiny' # nazwa zbioru danych
    url: 'https://www.dropbox.com/scl/fi/1s1igkml5otwzbsin2bfm/tiny_classics_train_val.tar?rlkey=yonpkg3qku5piqy4tqa5s3amp&dl=1' # adres do pobrania zbioru danych
    archive_ext: 'tar' # rodzaj archiwum: tar/zip/rar itd.
    test_folder: 'classics_train_val/example_val' # ścieżka do folderu wewnątrz archiwum ze zbiorem testowym
    train_folder: 'classics_train_val/example_train' # ścieżka do folderu wewnątrz archiwum ze zbiorem treningowym
    rmsd_csv_file_path: 'classics_train_val/scores.sc' # ścieżka do pliku CSV, w którym znajdują wartości RMSD dla każdej struktury RNA
    rmsd_csv_delimiter: ' ' # separator stosowany wewnątrz pliku CSV (zazwyczaj jest to przecinek albo spacja)
    rmsd_column_name: 'new_rms' # nazwa kolumny w pliku CSV z wartością RMSD
    csv_structure_column_name: 'description' # nazwa kolumny w pliku CSV z nazwą plików której dotyczy RMSD
    structure_column_ext: '.pdb' # rozszerzenie pliku stosowane w csv_structure_column_name
  download_preprocessed:
    train_url: 'https://www.dropbox.com/scl/fi/8jqgmqvf0ex46gqlaxn1q/train_tiny.h5?rlkey=w22wtod6qnyy43h4imcjgillw&dl=1' # adres do pobrania pliku H5 ze zbiorem treningowym
    test_url: 'https://www.dropbox.com/scl/fi/338heabf8sqrrv33gl64d/test_tiny.h5?rlkey=56wfxdrvbltw287v9ymbsodld&dl=1' # adres do pobrania pliku H5 ze zbiorem testowym
  features:
    atom_for_distance_calculations: "C1'"
    max_euclidean_distance: '16.0'
    regenerate_features_when_exists: True
  preprocessing_output:
    csv_path: data/output/
    h5_output: data/h5
  production: True
  
