data:
  download:
    name: 'testing' # nazwa zbioru danych
    url: 'https://dl.dropboxusercontent.com/s/r4hgjs4xgmkmaxj/classics_train_val.tar?dl=0' # adres do pobrania zbioru danych
    archive_ext: 'tar' # rodzaj archiwum: tar/zip/rar itd.
    test_folder: 'classics_train_val/example_val' # ścieżka do folderu wewnątrz archiwum ze zbiorem testowym
    train_folder: 'classics_train_val/example_train' # ścieżka do folderu wewnątrz archiwum ze zbiorem treningowym
    rmsd_csv_file_path: 'classics_train_val/scores.sc' # ścieżka do pliku CSV, w którym znajdują wartości RMSD dla każdej struktury RNA
    rmsd_csv_delimiter: ' ' # separator stosowany wewnątrz pliku CSV (zazwyczaj jest to przecinek albo spacja)
    rmsd_column_name: 'new_rms' # nazwa kolumny w pliku CSV z wartością RMSD
    csv_structure_column_name: 'description' # nazwa kolumny w pliku CSV z nazwą plików której dotyczy RMSD
    structure_column_ext: '.pdb' # rozszerzenie pliku stosowane w csv_structure_column_name
  download_preprocessed:
    train_url: 'https://www.dropbox.com/scl/fi/lbeqq01gh4v76i4570zbf/train.h5?rlkey=s54z7tfqx4tmkkztiy3y8oe69&dl=1' # adres do pobrania pliku H5 ze zbiorem treningowym
    test_url: 'https://www.dropbox.com/scl/fi/yciptkwgt9yhzqjawfj84/test.h5?rlkey=4x3v3dkcyj530bfw16wyilg2a&dl=1' # adres do pobrania pliku H5 ze zbiorem testowym
  features:
    atom_for_distance_calculations: "C1'"
    max_euclidean_distance: '16.0'
    regenerate_features_when_exists: True
  preprocessing_output:
    csv_path: data/output/
    h5_output: data/h5
  production: False
  
