version: "3.9"

name: rnaquanet
services:      
  rnaquanet:
    build:
      context: .
      dockerfile: Dockerfile
    image: rnaquanet:1.0
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ipc: host
    networks:
      - net
    ports:
      - "80:5000"
    restart: always
networks:
  net:
    driver: bridge