version: "3.9"

name: rnaquanet
services:      
  python_cuda:
    build:
      context: .
      dockerfile: Dockerfile
    image: python_cuda:1.0
    volumes:
      - python_cuda_volume:/app
      # - .:/app
      - ./logs:/opt/rnaquanet/logs/
    stdin_open: true 
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - net
networks:
  net:
    driver: bridge

volumes:
  redis:
  python_cuda_volume: