version: "3.9"

name: rnaquanet
services:
  rq-dashboard:
    image: eoranged/rq-dashboard
    depends_on:
      - python_cuda
    ports:
      - '8080:9181'
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379 
    networks:
      - net
      
  python_cuda:
    build:
      context: .
      dockerfile: Dockerfile
    image: python_cuda:1.0
    volumes:
      - python_cuda_volume:/app
      # - .:/app
      - ./logs:/opt/rnaquanet/logs/
    stdin_open: true 
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - net

  redis:
    image: redis:alpine
    restart: always
    command: redis-server && redis-cli flushall
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  redis:
  python_cuda_volume: