version: "3.9"

name: rnaquanet
services:      
  rnaquanet:
    build:
      context: .
      dockerfile: Dockerfile
    image: rnaquanet:1.0
    volumes:
      - .:/app
    stdin_open: true 
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - net
    ports:
      - "5000:5000"
      - "5173:5173"
networks:
  net:
    driver: bridge