name: 'rnaquadataset' # nazwa zbioru danych
tools_path: '/app/tools' # ścieżka do folderu z narzędziami zewnętrznymi wykorzystywanymi w pipeline
verbose: True
data:
  path: '/app/data' # ścieżka do folderu gdzie mają być zapisywane dane
  download:
    url: 'http://rnasolo.cs.put.poznan.pl/media/described_structures.tar.gz' # adres do pobrania zbioru danych
    archive_ext: 'tar.gz' # rodzaj archiwum: tar/tar.gz
    train_folder: 'train' # ścieżka do folderu wewnątrz archiwum ze zbiorem treningowym
    val_folder: 'val' # ścieżka do folderu wewnątrz archiwum ze zbiorem walidacyjnym
    test_folder: 'test' # ścieżka do folderu wewnątrz archiwum ze zbiorem testowym
    train_csv: 'train.csv' # ścieżka do pliku CSV, w którym znajdują wartości RMSD dla każdej struktury RNA zbioru treningowego
    val_csv: 'val.csv' # ścieżka do pliku CSV, w którym znajdują wartości RMSD dla każdej struktury RNA zbioru walidacyjnego
    test_csv: 'test.csv' # ścieżka do pliku CSV, w którym znajdują wartości RMSD dla każdej struktury RNA zbioru testowego
    csv_delimiter: ',' # separator stosowany wewnątrz pliku CSV (zazwyczaj jest to przecinek)
    csv_rmsd_column_name: 'rew_rmsd' # nazwa kolumny w pliku CSV z wartością RMSD
    csv_structure_column_name: 'description' # nazwa kolumny w pliku CSV z nazwą plików której dotyczy RMSD
  download_preprocessed:
    train_url: 'https://www.dropbox.com/scl/fi/6c7878deyfju4z1keud91/train_rna.h5?rlkey=mozyw4pv8uk38ku70ebqynnit&dl=1' # adres do pobrania pliku H5 ze zbiorem treningowym
    val_url: 'https://www.dropbox.com/scl/fi/zpxunzh1q9qbfwuay74rf/val_rna.h5?rlkey=s5unnan8nodk4hbfuweb11fa3&dl=1' # adres do pobrania pliku H5 ze zbiorem walidacyjnym
    test_url: 'https://www.dropbox.com/scl/fi/jcd2qrbo3dojkml2zfoq0/test_rna.h5?rlkey=k7ev48mvo0uwprb5lp0fo139z&dl=1' # adres do pobrania pliku H5 ze zbiorem testowym
  features:
    atom_for_distance_calculations: "C1'"
    max_euclidean_distance: '16.0'
    regenerate_features_when_exists: True
network:
  model_output_path: '/app/models'
  hidden_dim: 128
  layer_type: 4
  num_of_heads: 1
  num_of_layers: 8
  num_of_node_features: 96
  batch_norm: False
  gat_dropout: 0.1
  lr: 0.0001
  weight_decay: 0.2
  scheduler_step_size: 10
  scheduler_gamma: 0.5
  batch_size: 1000
  num_workers: 1
  shuffle_train: True
  shuffle_val: False
  shuffle_test: False
  max_epochs: 50
